version: '3'

services:
  solvnote:
    image: ghcr.io/yumumao/solvnote:latest
    container_name: solvnote
    restart: always
    ports:
      - "3000:3000"
    environment:
      # NEXTAUTH_URL 根据实际情况设置你的信息
      #- NEXTAUTH_URL=http://your_domain_name:3000
      - NEXTAUTH_SECRET=your_secret_key
    volumes:
      # Persist the SQLite database
      - ./data:/app/data
      - ./config:/app/config
