// @vitest-environment node
import {beforeEach,it,expect,vi} from "vitest";
const m=vi.hoisted(()=>({session:vi.fn(),live:vi.fn(),list:vi.fn(),create:vi.fn(),update:vi.fn(),remove:vi.fn(),reset:vi.fn()}));
vi.mock("next-auth",()=>({getServerSession:m.session}));
vi.mock("@/lib/auth",()=>({authOptions:{}}));
vi.mock("@/lib/prisma",()=>({prisma:{user:{findUnique:m.live,findMany:m.list}}}));
vi.mock("@/lib/user-management/rate-limit",()=>({consumeAuthLimit:async()=>true}));
vi.mock("@/lib/user-management/users",()=>({createManagedUser:m.create,updateManagedUser:m.update,deleteManagedUser:m.remove,resetManagedPassword:m.reset}));
import {GET,POST} from "@/app/api/admin/users/route";
import {PATCH,DELETE} from "@/app/api/admin/users/[id]/route";
import {POST as RESET} from "@/app/api/admin/users/[id]/reset-password/route";
import {UserManagementError as E} from "@/lib/user-management/errors";
const request=(method="GET",body:unknown={},headers={})=>new Request("https://app.invalid/api/admin/users",{method,headers:{"Content-Type":"application/json",...headers},...(method==="GET"?{}:{body:JSON.stringify(body)})});
const ctx={params:Promise.resolve({id:"target"})};
beforeEach(()=>{vi.resetAllMocks();m.session.mockResolvedValue({user:{id:"admin",role:"admin",sessionVersion:2}});m.live.mockResolvedValue({id:"admin",role:"admin",isActive:true,expiresAt:null,sessionVersion:2,mustChangePassword:false});m.list.mockResolvedValue([{id:"safe"}]);m.create.mockResolvedValue({user:{id:"new"}});m.update.mockResolvedValue({id:"target",revision:2});m.remove.mockResolvedValue({ok:true});m.reset.mockResolvedValue({temporaryPassword:"synthetic-one-time-only"});});
it("lists only explicit safe fields with no-store",async()=>{const r=await GET(request());expect(r.status).toBe(200);expect(r.headers.get("cache-control")).toBe("no-store");const select=m.list.mock.calls[0][0].select;expect(select.expiresAt).toBe(true);expect(select.revision).toBe(true);expect(select.password).toBeUndefined();expect(select.sessionVersion).toBeUndefined();});
it.each([null,{id:"admin",role:"user",isActive:true,sessionVersion:2},{id:"admin",role:"admin",isActive:false,sessionVersion:2},{id:"admin",role:"admin",isActive:true,expiresAt:new Date(0),sessionVersion:2},{id:"admin",role:"admin",isActive:true,sessionVersion:3},{id:"admin",role:"admin",isActive:true,sessionVersion:2,mustChangePassword:true}])("rejects stale admin JWTs across every endpoint",async live=>{m.live.mockResolvedValue(live);expect((await GET(request())).status).toBe(403);expect((await POST(request("POST"))).status).toBe(403);expect((await PATCH(request("PATCH"),ctx)).status).toBe(403);expect((await DELETE(request("DELETE"),ctx)).status).toBe(403);expect((await RESET(request("POST"),ctx)).status).toBe(403);expect(m.list).not.toHaveBeenCalled();expect(m.remove).not.toHaveBeenCalled();});
it("rejects a missing session",async()=>{m.session.mockResolvedValue(null);expect((await GET(request())).status).toBe(401);});
it("forwards actor, target and revision rather than trusting body userId",async()=>{await PATCH(request("PATCH",{revision:1,expirationDays:30}),ctx);expect(m.update).toHaveBeenCalledWith("admin","target",{revision:1,expirationDays:30},expect.any(Date),2);await DELETE(request("DELETE",{revision:1}),ctx);expect(m.remove).toHaveBeenCalledWith("admin","target",{revision:1},expect.any(Date),2);});
it.each([["REVISION_CONFLICT",409],["LAST_ADMIN",409],["SELF_ACTION_DENIED",409]])("preserves fail-closed service policy %s",async(code,status)=>{m.update.mockRejectedValue(new E(code as string,status as number));expect((await PATCH(request("PATCH",{revision:1}),ctx)).status).toBe(status);});
it("rejects cross-origin mutations",async()=>{expect((await DELETE(request("DELETE",{revision:1},{Origin:"https://evil.invalid"}),ctx)).status).toBe(403);expect(m.remove).not.toHaveBeenCalled();});
it("returns one-time password responses without caching",async()=>{const r=await RESET(request("POST",{revision:1}),ctx);expect(r.status).toBe(200);expect(r.headers.get("cache-control")).toBe("no-store");});
