// @vitest-environment node
// Synthetic fixture generated by ScanDex's Python mapper + browser WebCrypto.
// It contains no real configuration, and the password is test-only.
import { describe, it, expect } from "vitest";
import fixture from "../fixtures/scandex-portable-v1.json";
import { openExport } from "@/lib/ai-config/crypto";
describe("ScanDex portable v1 interoperability", () => {
    it("decrypts the real exporter output and validates the shared schema", async () => {
        const config = await openExport(fixture, "test-only-password");
        expect(config.version).toBe(1);
        expect(config.providers).toHaveLength(4);
        expect(config.models).toHaveLength(4);
        expect(config.chains.text).toHaveLength(2);
        expect(config.chains.vision).toHaveLength(2);
        expect(config).not.toHaveProperty("proxy");
        expect(config).not.toHaveProperty("consumer_token");
    });
    it("rejects a different password", async () => {
        await expect(
            openExport(fixture, "wrong-test-password"),
        ).rejects.toThrow();
    });
});

// Generated with the current ScanDex Python mapper + actual browser export
// function (not the notebook sealer). Synthetic only, no private settings.
import longFixture from "../fixtures/scandex-portable-long-v1.json";
import blockedFixture from "../fixtures/scandex-portable-blocked-v1.json";
it("accepts a current ScanDex export with a 200-character upstream/display model name", async () => {
    const config = await openExport(longFixture, "synthetic-互通-passphrase");
    expect(config.models[0].model).toBe("m".repeat(200));
    expect(config.models[0].name).toBe(config.models[0].model);
    expect(config.chains.text).toEqual([config.models[0].id]);
});
it("diagnoses a current ScanDex export containing a disabled HTTP/query connection", async () => {
    await expect(openExport(blockedFixture, "synthetic-互通-passphrase")).rejects.toMatchObject({
        message: "IMPORT_CONFIG_INCOMPATIBLE",
        issues: [{ path: "providers.1.baseUrl", reason: "URL_POLICY" }],
    });
});
