import {act} from "react";
import {createRoot, type Root} from "react-dom/client";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
vi.mock("@/components/geogebra-demo",()=>({GeogebraDemo:()=> <div data-testid="external-geogebra">external</div>}));
import {ConstructionPreview,DrawingResultPreview} from "@/components/auxiliary-drawing";
import {compileConstruction,type ConstructionPlan} from "@/lib/ai-drawing/construction";
const plan:ConstructionPlan={title:"合成辅助线",points:[{id:"A",x:1000,y:1000},{id:"B",x:1004,y:1000},{id:"C",x:1000,y:1004}],segments:[["A","B"],["B","C"],["C","A"]],steps:[{description:"取中点",operation:{kind:"midpoint",id:"M",a:"A",b:"B"}},{description:"连接中点",operation:{kind:"segment",a:"C",b:"M"}}]};
let host:HTMLDivElement,root:Root;
beforeEach(()=>{vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT",true);host=document.createElement("div");document.body.append(host);root=createRoot(host)});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.unstubAllGlobals()});
async function render(element:React.ReactNode){await act(async()=>root.render(element))}
async function click(label:string){const b=[...host.querySelectorAll("button")].find(b=>b.textContent===label);expect(b).toBeTruthy();await act(async()=>b!.click())}
describe("offline auxiliary construction preview",()=>{
 it("renders a fitted local SVG without mounting the external applet",async()=>{await render(<ConstructionPreview plan={plan}/>);const svg=host.querySelector('svg[role="img"]');expect(svg).not.toBeNull();expect(svg?.getAttribute("aria-label")).toContain("辅助线");expect(host.querySelector('[data-testid="external-geogebra"]')).toBeNull();expect(svg?.querySelectorAll("line")).toHaveLength(4);expect(svg?.querySelectorAll("circle")).toHaveLength(4);for(const p of svg!.querySelectorAll("circle")){expect(Number(p.getAttribute("cx"))).toBeGreaterThan(10);expect(Number(p.getAttribute("cx"))).toBeLessThan(790);expect(Number(p.getAttribute("cy"))).toBeGreaterThan(10);expect(Number(p.getAttribute("cy"))).toBeLessThan(490)}});
 it("uses the same validated calculations, supports previous/next steps and keeps the original",async()=>{const before=JSON.stringify(plan);await render(<ConstructionPreview plan={plan}/>);await click("上一步");expect(host.querySelectorAll('svg[role="img"] line')).toHaveLength(3);await click("上一步");expect(host.querySelectorAll('svg[role="img"] circle')).toHaveLength(3);await click("下一步");expect(host.querySelectorAll('svg[role="img"] circle')).toHaveLength(4);expect(JSON.stringify(plan)).toBe(before)});
 it("only loads dynamic geometry on request and keeps the local diagram",async()=>{await render(<ConstructionPreview plan={plan}/>);await click("打开GeoGebra动态演示（需联网）");expect(host.querySelector('[data-testid="external-geogebra"]')).not.toBeNull();expect(host.querySelector('svg[role="img"]')).not.toBeNull()});
 it("restores local previews from drawing task results",async()=>{await render(<DrawingResultPreview result={{type:"construction",plan}}/>);expect(host.querySelector('svg[role="img"]')).not.toBeNull()});
 it("reports returned raster image load failures without submitting again",async()=>{await render(<DrawingResultPreview result={{type:"image_edit",imageDataUrl:"data:image/png;base64,YQ=="}}/>);const img=host.querySelector("img")!;await act(async()=>img.dispatchEvent(new Event("error")));expect(host.querySelector('[role="alert"]')?.textContent).toContain("图片加载失败");expect(host.querySelector('a[download]')).not.toBeNull()});
 it("retains strict invalid-construction rejection",async()=>{await render(<DrawingResultPreview result={{type:"construction",plan:{...plan,steps:[{description:"无效",operation:{kind:"segment",a:"A",b:"Z"}}]}}}/>);expect(host.textContent).toContain("构造关系无效");expect(host.querySelector('svg[role="img"]')).toBeNull()});
 it("exposes already-calculated geometry for all supported operations",()=>{const compiled=compileConstruction({...plan,steps:[{description:"垂足",operation:{kind:"foot",id:"F",point:"C",a:"A",b:"B"}},{description:"旋转",operation:{kind:"rotate",id:"R",point:"B",center:"A",degrees:90}},{description:"相交",operation:{kind:"intersection",id:"I",a:"A",b:"B",c:"B",d:"C"}}]});expect(compiled.geometry.points.find(p=>p.id==="F")).toMatchObject({x:1000,y:1000,step:1});expect(compiled.geometry.points.find(p=>p.id==="R")?.y).toBeCloseTo(1004);expect(compiled.geometry.points.find(p=>p.id==="I")).toMatchObject({x:1004,y:1000,step:3})});
});
