// @vitest-environment node
import {it,expect,vi} from "vitest";
import sharp from "sharp";
vi.mock("@/lib/ai/chain",()=>({callChain:vi.fn()}));vi.mock("@/lib/ai-access/account",()=>({requireLiveAiUser:vi.fn()}));
import {composeIllustrationPrompt} from "@/lib/ai-drawing/illustration-reference";
import {parseIllustrationDescription,validateDescriptionInput} from "@/lib/ai-drawing/illustration-description";
import {JobInputSchema} from "@/lib/ai-jobs/schema";
it("combines all reviewed sources and geometry safeguards without truncation",()=>{const p=composeIllustrationPrompt({text:"半径4",description:"圆心O",requirements:"条件".repeat(900),kind:"geometry"});for(const value of ["半径4","圆心O","90°","不补完整圆","条件".repeat(900)])expect(p).toContain(value);expect(p.length).toBeGreaterThan(1500)});
it("does not apply geometry-only style to creative illustrations",()=>{const p=composeIllustrationPrompt({text:"风景",description:"",requirements:"",kind:"creative"});expect(p).toContain("创作配图");expect(p).not.toContain("90°");expect(p).not.toContain("原图描述：")});
it("accepts only a bounded description and uncertainty list",()=>{expect(parseIllustrationDescription(JSON.stringify({description:"  合成圆弧  ",uncertainties:[]}))).toEqual({description:"合成圆弧",uncertainties:[]})});
it.each(["not JSON",JSON.stringify({description:"",uncertainties:[]}),JSON.stringify({description:"a".repeat(4001),uncertainties:[]}),JSON.stringify({description:"ok",uncertainties:Array(13).fill("?")}),JSON.stringify({description:"ok",uncertainties:["a".repeat(301)]}),JSON.stringify({description:"ok",uncertainties:[],answer:"must not be accepted"})])("rejects malformed or oversized description %# with a sanitized error",raw=>{expect(()=>parseIllustrationDescription(raw)).toThrow("AI_DESCRIPTION_INVALID")});
it.each(["png","jpeg","webp"] as const)("accepts valid single-frame %s",async format=>{const bytes=await sharp({create:{width:3,height:3,channels:3,background:"white"}}).toFormat(format).toBuffer();await expect(validateDescriptionInput(JobInputSchema.parse({confirmDescription:true,imageBase64:"data:image/"+format+";base64,"+bytes.toString("base64")}))).resolves.toBeUndefined()});
it.each(["missing-confirm","mismatched-mime","invalid-bytes","oversized","question","review"])("rejects invalid description input %s",async kind=>{const bytes=await sharp({create:{width:3,height:3,channels:3,background:"white"}}).png().toBuffer();const input=JobInputSchema.parse({confirmDescription:kind==="missing-confirm"?undefined:true,imageBase64:kind==="invalid-bytes"?"data:image/png;base64,YQ==":kind==="oversized"?"data:image/png;base64,"+"A".repeat(8*1024*1024+4):"data:image/"+(kind==="mismatched-mime"?"jpeg":"png")+";base64,"+bytes.toString("base64"),questionText:kind==="question"?"not allowed":"",review:kind==="review"});await expect(validateDescriptionInput(input)).rejects.toThrow("INVALID_REQUEST")});
